### ISSUE TITLE
2.0能用贴纸吗？

### ISSUE THREAD

**Issue by he426100** [anhkgg/Huawei_PCManager_NB#10]
1.0的时候搞好了贴纸，前段时间用改bios的方法装上了2.0，现在装了这个，怎么重新弄贴纸呢？

**Comment by Atlands** [comment]
通过nfc标签编辑应用清空贴纸信息，然后重写

**Comment by he426100** [comment]
有推荐的吗？试了很多个都没法编辑

**Comment by Atlands** [comment]
Google play下载NFC TagWriter，擦除标签数据 ，按照教程重写。
华为手机会先于所下应用识别一碰传标签，所以你需要使用其他品牌的nfc手机擦除数据。
或者使用冰箱类工具冻结华为分享等应用，然后使用所下应用擦除数据

**Comment by he426100** [comment]
明白了，谢谢
