### ISSUE TITLE
改善国内下载速度的解决方案

### ISSUE THREAD

**Issue by Tim-Paik** [anhkgg/Huawei_PCManager_NB#2]
我在码云上克隆了一份，地址为https://gitee.com/timpaik/Huawei_PCManager_NB
如有侵权请联系我，仅为克隆没有做任何改变，原作者地址已附上

**Comment by anhkgg** [comment]
已提供百度网盘下载
链接:https://pan.baidu.com/s/1YsPlMJ2IVW7y-7vJYV9iZw 提取码:tmm9 复制这段内容后打开百度网盘手机App，操作更方便哦
